"""empty message

Revision ID: 14598d5fd710
Revises: 5d730681096c
Create Date: 2020-05-02 21:07:12.464789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14598d5fd710'
down_revision = '5d730681096c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
